/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package serenty.presentaciones.paciente;

import serenty.presentaciones.psicologo.*;
import serenty.clases.ConexionDB;
import com.mysql.jdbc.Connection;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import com.mysql.jdbc.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import serenty.clases.ConsultasDB;
import serenty.clases.UsuarioActivo;


/**
 *
 * @author User
 */
public class CitasPaciente extends javax.swing.JInternalFrame {
    ConexionDB connection = new ConexionDB ();
    Connection cn = connection.conectar();
    
    /**
     * Creates new form TODAC
     */
    
    public CitasPaciente() {
        initComponents();
        try{
            cargarListaPsicologos();
        }catch(Exception e){
            
        }
    }
    
    public void cargarListaPsicologos() {
        
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        //Agendada - Reagendada - Finalizada - Cancelada

        try {        
            PreparedStatement preparedStatement = (PreparedStatement) cn.prepareStatement(ConsultasDB.SELECT_ALL_PSICOLOGO);
            ResultSet resultado = preparedStatement.executeQuery();

            while (resultado.next()) {
                String nombre = resultado.getString("NOMBRE_PSICOLOGO");
                String apellido = resultado.getString("APELLIDO_PSICOLOGO");
                String nombreApellido = nombre + " " + apellido;
                modelo.addElement(nombreApellido);
            }

            listaPsico.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hora = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        fechaCita = new com.toedter.calendar.JCalendar();
        listaPsico = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        modalidad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        NUEVO1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("mariana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 229, 199));
        jLabel1.setText("AGENDAR CITAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        jPanel2.setBackground(new java.awt.Color(241, 231, 197));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        jLabel2.setText("Psicólogos:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 153, 22));

        jLabel3.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        jLabel3.setText("Fecha:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        jLabel4.setText("Modalidad:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 178, 20));

        hora.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "07:00:00", "07:30:00", "08:00:00", "08:30:00", "09:00:00", "09:30:00", "10:00:00", "10:30:00", "11:00:00", "11:30:00", "12:00:00", "14:00:00", "14:30:00", "15:00:00", "15:30:00", "16:00:00", "16:30:00", "17:00:00", "17:30:00", "18:00:00", "18:30:00", "19:00:00" }));
        hora.setToolTipText("");
        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });
        jPanel2.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 160, 30));

        jLabel5.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        jLabel5.setText("Dirección Cita:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 100, 20));
        jPanel2.add(fechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 380, 210));

        listaPsico.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        listaPsico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Virtual", "Presencial" }));
        listaPsico.setToolTipText("");
        listaPsico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPsicoActionPerformed(evt);
            }
        });
        jPanel2.add(listaPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 160, 30));

        jLabel6.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        jLabel6.setText("Hora:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 50, 20));

        direccion.setBackground(new java.awt.Color(241, 231, 197));
        direccion.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        direccion.setBorder(null);
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                direccionKeyReleased(evt);
            }
        });
        jPanel2.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 200, 23));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 200, 11));

        modalidad.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        modalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Virtual", "Presencial" }));
        modalidad.setToolTipText("");
        modalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalidadActionPerformed(evt);
            }
        });
        jPanel2.add(modalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 160, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/clock.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/location.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/online-meeting.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/user (1).png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/calendar (2).png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jPanel3.setBackground(new java.awt.Color(182, 212, 187));

        jButton1.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        jButton1.setText("AGENDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NUEVO1.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        NUEVO1.setText("LIMPIAR");
        NUEVO1.setToolTipText("");
        NUEVO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVO1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
            .addComponent(NUEVO1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NUEVO1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String nombreApellido = listaPsico.getSelectedItem().toString();
        String nombrePsico = nombreApellido.substring(0, nombreApellido.indexOf(" "));
        String apellidoPsico = nombreApellido.substring(nombreApellido.indexOf(" ") + 1);
        
        String modali = modalidad.getSelectedItem().toString();
        String hora_cita = hora.getSelectedItem().toString();
        String direc = direccion.getText();
        Date fecha_cita = fechaCita.getDate();
        String estadoCita = "Agendada";
        
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String fecha_formateada = simpleDateFormat.format(fecha_cita);
        
        Calendar calendarManana = Calendar.getInstance();
        calendarManana.add(Calendar.DAY_OF_YEAR, 1);
        calendarManana.set(Calendar.HOUR_OF_DAY, 0);
        calendarManana.set(Calendar.MINUTE, 0);
        calendarManana.set(Calendar.SECOND, 0);
        calendarManana.set(Calendar.MILLISECOND, 0);
        Date manana = calendarManana.getTime();
        
        if (nombreApellido.isEmpty()||modali.isEmpty()||modali.equals("Seleccionar")||hora_cita.isEmpty()||hora_cita.equals("Sleccionar")||direc.isEmpty()||fecha_cita == null) {
            JOptionPane.showMessageDialog(jPanel2, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if (fecha_cita.before(manana)){
                JOptionPane.showMessageDialog(null, "Debes agendar citas a partir de mañana", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                try {
                    UsuarioActivo idUsuario = UsuarioActivo.getInstance();
                    
                    PreparedStatement psConsultaPaci = (PreparedStatement) cn.prepareStatement(String.format(ConsultasDB.SELECT_IDPACIENTE_IDUSUARIO, String.valueOf(idUsuario.getIdUsuario())));
                    ResultSet rsConsultaPaci = psConsultaPaci.executeQuery();
                    rsConsultaPaci.next();
                    String idPaci = rsConsultaPaci.getString("ID_PACIENTE");
                    
                    PreparedStatement psConsultaPsico = (PreparedStatement) cn.prepareStatement(String.format(ConsultasDB.SELECT_IDPSICOLOGO_NOMBRE, nombrePsico, apellidoPsico));
                    ResultSet rsConsultaPsico = psConsultaPsico.executeQuery();
                    rsConsultaPsico.next();
                    String idPsico = rsConsultaPsico.getString("ID_PSICOLOGO");

                    PreparedStatement psCita = (PreparedStatement) cn.prepareStatement(String.format(ConsultasDB.INSERT_INTO_CITA, fecha_formateada, hora_cita, modali, direc, estadoCita));
                    psCita.executeUpdate();
                                        
                    PreparedStatement psCitaUs = (PreparedStatement) cn.prepareStatement(String.format(ConsultasDB.INSERT_INTO_CITAUSUARIO, idPaci, idPsico));
                    psCitaUs.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Datos registrados correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
       
    }//GEN-LAST:event_jPanel2MouseClicked

    private void NUEVO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVO1ActionPerformed
        // TODO add your handling code here 
        listaPsico.setSelectedItem("Seleccionar");
        hora.setSelectedItem("Seleccionar");
        direccion.setText("");
    }//GEN-LAST:event_NUEVO1ActionPerformed

    private void listaPsicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPsicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaPsicoActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void direccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionKeyReleased

    private void modalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modalidadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NUEVO1;
    private javax.swing.JTextField direccion;
    private com.toedter.calendar.JCalendar fechaCita;
    private javax.swing.JComboBox<String> hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> listaPsico;
    private javax.swing.JComboBox<String> modalidad;
    // End of variables declaration//GEN-END:variables
}
