/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package serenty.presentaciones.inicio;

import serenty.clases.ConexionDB;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import serenty.clases.Constantes;
import serenty.clases.ConsultasDB;

/**
 *
 * @author User
 */
public class RegistrarPacienteUsuario extends javax.swing.JFrame {
    ConexionDB connection = new ConexionDB ();
    Connection cn = connection.conectar();
    /**
     * Creates new form REGISTROS
     */
    public RegistrarPacienteUsuario() {
        initComponents();
        AVISO.setVisible(false);
        this.setLocationRelativeTo(null);
    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        telefonoPaciente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        numIdentidad = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        HIDE = new javax.swing.JLabel();
        SHOW = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cerrar1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        selectGenero = new javax.swing.JComboBox<>();
        AVISO = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        correoPaciente = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        nombresPaciente = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        passwordPaciente = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        selectIdentidad = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        fechaNacimiento = new com.toedter.calendar.JCalendar();
        apellidosPaciente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(182, 212, 187));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/image.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("mariana", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 60, 60));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Regístrate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(241, 231, 197));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/email.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        telefonoPaciente.setBackground(new java.awt.Color(241, 231, 197));
        telefonoPaciente.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        telefonoPaciente.setBorder(null);
        telefonoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoPacienteActionPerformed(evt);
            }
        });
        telefonoPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telefonoPacienteKeyReleased(evt);
            }
        });
        jPanel2.add(telefonoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 279, 23));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 279, 11));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/user (1).png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        numIdentidad.setBackground(new java.awt.Color(241, 231, 197));
        numIdentidad.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        numIdentidad.setBorder(null);
        numIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numIdentidadActionPerformed(evt);
            }
        });
        jPanel2.add(numIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 279, 23));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 287, 11));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/padlock.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 285, 11));

        HIDE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/hide (2).png"))); // NOI18N
        HIDE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HIDEMouseClicked(evt);
            }
        });
        jPanel2.add(HIDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        SHOW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/show.png"))); // NOI18N
        SHOW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SHOWMouseClicked(evt);
            }
        });
        jPanel2.add(SHOW, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel6.setText("Apellido:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, 20));

        jLabel7.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel7.setText("Fecha Nacimiento:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, 14));

        jLabel8.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel8.setText("Teléfono:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, 20));

        jLabel10.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel10.setText("Género:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, 20));

        cerrar1.setFont(new java.awt.Font("mariana", 0, 18)); // NOI18N
        cerrar1.setForeground(new java.awt.Color(16, 60, 60));
        cerrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar1.setText("x");
        cerrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrar1MouseClicked(evt);
            }
        });
        jPanel2.add(cerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 56, 53));

        jButton1.setBackground(new java.awt.Color(182, 212, 187));
        jButton1.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        jButton1.setText("Registrarse");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 138, 46));

        jLabel11.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/VOLVER.png"))); // NOI18N
        jLabel11.setText("VOLVER");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        selectGenero.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        selectGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Masculino", "Femenino", "Otro" }));
        selectGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectGeneroActionPerformed(evt);
            }
        });
        jPanel2.add(selectGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 150, 30));

        AVISO.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        AVISO.setForeground(new java.awt.Color(204, 0, 0));
        AVISO.setText("Error en el correo");
        jPanel2.add(AVISO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 130, -1));

        jLabel9.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel9.setText("Correo Electrónico:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 55, -1, 20));

        correoPaciente.setBackground(new java.awt.Color(241, 231, 197));
        correoPaciente.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        correoPaciente.setBorder(null);
        correoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoPacienteActionPerformed(evt);
            }
        });
        correoPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                correoPacienteKeyReleased(evt);
            }
        });
        jPanel2.add(correoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 279, 23));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 279, 11));

        jLabel12.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel12.setText("Nombre:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, 20));

        nombresPaciente.setBackground(new java.awt.Color(241, 231, 197));
        nombresPaciente.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        nombresPaciente.setBorder(null);
        nombresPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresPacienteActionPerformed(evt);
            }
        });
        nombresPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombresPacienteKeyReleased(evt);
            }
        });
        jPanel2.add(nombresPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 279, 23));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 279, 10));

        jLabel13.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel13.setText("Contraseña:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 20));

        passwordPaciente.setBackground(new java.awt.Color(241, 231, 197));
        passwordPaciente.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        passwordPaciente.setBorder(null);
        passwordPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPacienteActionPerformed(evt);
            }
        });
        jPanel2.add(passwordPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 279, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 285, 11));

        jLabel14.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel14.setText("Tipo Identificación:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, 20));

        selectIdentidad.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        selectIdentidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Cédula", "T.Identidad" }));
        selectIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectIdentidadActionPerformed(evt);
            }
        });
        jPanel2.add(selectIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 150, 30));

        jLabel15.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel15.setText("N° Identificación:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, 14));
        jPanel2.add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 360, 200));

        apellidosPaciente.setBackground(new java.awt.Color(241, 231, 197));
        apellidosPaciente.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        apellidosPaciente.setBorder(null);
        apellidosPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosPacienteActionPerformed(evt);
            }
        });
        apellidosPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                apellidosPacienteKeyReleased(evt);
            }
        });
        jPanel2.add(apellidosPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 279, 23));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/id-card (2).png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/user (1).png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/telephone (1).png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/calendar (2).png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/toilet.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/id-card (2).png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoPacienteActionPerformed

    private void HIDEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HIDEMouseClicked
        // TODO add your handling code here:
        passwordPaciente.setEchoChar((char)0);
        HIDE.setVisible(false);
        HIDE.setVisible(false);
        SHOW.setVisible(true);
        SHOW.setVisible(true);
    }//GEN-LAST:event_HIDEMouseClicked

    private void SHOWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SHOWMouseClicked
        // TODO add your handling code here:
        passwordPaciente.setEchoChar((char)8226);
        HIDE.setVisible(true);
        HIDE.setVisible(true);
        SHOW.setVisible(false);
        SHOW.setVisible(false);
    }//GEN-LAST:event_SHOWMouseClicked

    private void cerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerrar1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String correo = correoPaciente.getText();
        String contrasenia = passwordPaciente.getText();
        String rol = "Paciente";
        String id_usuario = numIdentidad.getText();
        String tipoId_paciente = selectIdentidad.getSelectedItem().toString();
        String nombres = nombresPaciente.getText();
        String apellidos = apellidosPaciente.getText();
        String telefono = telefonoPaciente.getText();
        String genero = selectGenero.getSelectedItem().toString();
        Date fecha_naci = fechaNacimiento.getDate();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String fecha_formateada = simpleDateFormat.format(fecha_naci);
        Date fechaLimite = new Date(112, 0, 1);
        int test_presentado = 0;
        
        if(genero.equals("Masculino")){
            genero = "M";
        }else if(genero.equals("Femenino")){
            genero = "F";
        }else if(genero.equals("Otro")){
            genero = "O";
        }
        
        //VALIDACION
        if (correo.isEmpty()||contrasenia.isEmpty()||id_usuario.isEmpty()||tipoId_paciente.isEmpty()||tipoId_paciente.equals("Seleccionar")||nombres.isEmpty()||apellidos.isEmpty()||telefono.isEmpty()||genero.isEmpty()||genero.equals("Seleccionar")||fecha_naci == null) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (fecha_naci.before(fechaLimite)) {
                if (telefono.matches("\\d+") && id_usuario.matches("\\d+")){
                    if(Constantes.validarCorreo(correo)){
                        if (Constantes.validarNombre(nombres) && Constantes.validarNombre(apellidos)) {
                            AVISO.setVisible(false);

                            try{
                                PreparedStatement psUsuario = (PreparedStatement) cn.prepareStatement(String.format(ConsultasDB.INSERT_INTO_USUARIO, correo, contrasenia, rol));    
                                psUsuario.executeUpdate();

                                PreparedStatement psPaciente = (PreparedStatement) cn.prepareStatement(String.format(ConsultasDB.INSERT_INTO_PACIENTE, id_usuario, tipoId_paciente, nombres, apellidos, telefono, genero, fecha_formateada, test_presentado));
                                psPaciente.executeUpdate();

                                JOptionPane.showMessageDialog(null, "Datos registrados correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                                IniciarSesionUsuario iniciarSesionUsuario = new IniciarSesionUsuario();
                                iniciarSesionUsuario.setVisible(true);
                                this.setVisible(false);                                
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Los nombres y apellidos no pueden contener números o caracteres especiales", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        AVISO.setVisible(true);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Ingrese los datos número de identidad y teléfono", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Debe tener mínimo 10 años", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        OpcionesUsuario opcionesUsuario = new OpcionesUsuario();
        opcionesUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void telefonoPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoPacienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoPacienteKeyReleased

    private void numIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numIdentidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numIdentidadActionPerformed

    private void selectGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectGeneroActionPerformed

    private void correoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoPacienteActionPerformed

    private void correoPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoPacienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_correoPacienteKeyReleased

    private void nombresPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresPacienteActionPerformed

    private void nombresPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresPacienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresPacienteKeyReleased

    private void passwordPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPacienteActionPerformed

    private void selectIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectIdentidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectIdentidadActionPerformed

    private void apellidosPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosPacienteActionPerformed

    private void apellidosPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosPacienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosPacienteKeyReleased
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AVISO;
    private javax.swing.JLabel HIDE;
    private javax.swing.JLabel SHOW;
    private javax.swing.JTextField apellidosPaciente;
    private javax.swing.JLabel cerrar1;
    private javax.swing.JTextField correoPaciente;
    private com.toedter.calendar.JCalendar fechaNacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nombresPaciente;
    private javax.swing.JTextField numIdentidad;
    private javax.swing.JPasswordField passwordPaciente;
    private javax.swing.JComboBox<String> selectGenero;
    private javax.swing.JComboBox<String> selectIdentidad;
    private javax.swing.JTextField telefonoPaciente;
    // End of variables declaration//GEN-END:variables
void Limpiar(){
    
    telefonoPaciente.setText("");
    numIdentidad.setText("");
    telefonoPaciente.setText("");
 
}

}
