/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package serenty.presentaciones.inicio;

import serenty.clases.ConexionDB;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import javax.swing.JOptionPane;
import java.util.Date;
import java.io.File;
import java.text.SimpleDateFormat;
import serenty.clases.Constantes;
import serenty.clases.ConsultasDB;

/**
 *
 * @author User
 */
public class RegistrarPsicologoUsuario extends javax.swing.JFrame {
    ConexionDB connection = new ConexionDB ();
    Connection cn = connection.conectar();
    /**
     * Creates new form REGISTROS
     */
    public RegistrarPsicologoUsuario() {
        initComponents();
        AVISO.setVisible(false);
        this.setLocationRelativeTo(null);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        telefonoPsico = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        HIDE = new javax.swing.JLabel();
        SHOW = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cerrar1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        AVISO = new javax.swing.JLabel();
        passwordPsico = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        selectEntidad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        correoPsico = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        especialidad = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        apellidosPsico = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        selectGenero = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fechaNacimiento = new com.toedter.calendar.JCalendar();
        numIdentidad = new javax.swing.JTextField();
        nombresPsico = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(182, 212, 187));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/image.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("mariana", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 60, 60));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Regístrate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(241, 231, 197));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/email.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        telefonoPsico.setBackground(new java.awt.Color(241, 231, 197));
        telefonoPsico.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        telefonoPsico.setBorder(null);
        telefonoPsico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoPsicoActionPerformed(evt);
            }
        });
        telefonoPsico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telefonoPsicoKeyReleased(evt);
            }
        });
        jPanel2.add(telefonoPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 279, 23));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 279, 11));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/toilet.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/padlock.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 285, 11));

        HIDE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/hide (2).png"))); // NOI18N
        HIDE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HIDEMouseClicked(evt);
            }
        });
        jPanel2.add(HIDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        SHOW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/show.png"))); // NOI18N
        SHOW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SHOWMouseClicked(evt);
            }
        });
        jPanel2.add(SHOW, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel6.setText("Teléfono:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, 20));

        jLabel7.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, 14));

        jLabel8.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel8.setText("Contraseña:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        jLabel10.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel10.setText("N° Identificación:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 20));

        cerrar1.setFont(new java.awt.Font("mariana", 0, 18)); // NOI18N
        cerrar1.setForeground(new java.awt.Color(16, 60, 60));
        cerrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar1.setText("x");
        cerrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrar1MouseClicked(evt);
            }
        });
        jPanel2.add(cerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 56, 53));

        jButton1.setBackground(new java.awt.Color(182, 212, 187));
        jButton1.setFont(new java.awt.Font("COCOGOOSE ", 0, 14)); // NOI18N
        jButton1.setText("Registrarse");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 138, 46));

        jLabel11.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/VOLVER.png"))); // NOI18N
        jLabel11.setText("VOLVER");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        AVISO.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        AVISO.setForeground(new java.awt.Color(204, 0, 0));
        AVISO.setText("Error en el correo");
        jPanel2.add(AVISO, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 130, -1));

        passwordPsico.setBackground(new java.awt.Color(241, 231, 197));
        passwordPsico.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        passwordPsico.setBorder(null);
        passwordPsico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPsicoActionPerformed(evt);
            }
        });
        jPanel2.add(passwordPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 279, 30));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 285, 11));

        selectEntidad.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        selectEntidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "EPS", "IPS", "ARL" }));
        selectEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectEntidadActionPerformed(evt);
            }
        });
        jPanel2.add(selectEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 150, 30));

        jLabel9.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel9.setText("Correo Electrónico:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 55, -1, 20));

        correoPsico.setBackground(new java.awt.Color(241, 231, 197));
        correoPsico.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        correoPsico.setBorder(null);
        correoPsico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoPsicoActionPerformed(evt);
            }
        });
        correoPsico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                correoPsicoKeyReleased(evt);
            }
        });
        jPanel2.add(correoPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 81, 279, 23));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 279, 11));

        jLabel12.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel12.setText("Nombre:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, 20));

        especialidad.setBackground(new java.awt.Color(241, 231, 197));
        especialidad.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        especialidad.setBorder(null);
        especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadActionPerformed(evt);
            }
        });
        especialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                especialidadKeyReleased(evt);
            }
        });
        jPanel2.add(especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 279, 23));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 279, 11));

        jLabel13.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel13.setText("Apellido:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, 20));

        apellidosPsico.setBackground(new java.awt.Color(241, 231, 197));
        apellidosPsico.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        apellidosPsico.setBorder(null);
        apellidosPsico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosPsicoActionPerformed(evt);
            }
        });
        apellidosPsico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                apellidosPsicoKeyReleased(evt);
            }
        });
        jPanel2.add(apellidosPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 279, 23));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 279, 11));

        jLabel14.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel14.setText("Género:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, 14));

        selectGenero.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        selectGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Masculino", "Femenino" }));
        selectGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectGeneroActionPerformed(evt);
            }
        });
        jPanel2.add(selectGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 150, 30));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 285, 11));

        jLabel16.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel16.setText("Tipo Entidad:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, 14));

        jLabel17.setFont(new java.awt.Font("COCOGOOSE ", 0, 12)); // NOI18N
        jLabel17.setText("Especialidad:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, 14));
        jPanel2.add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 380, 200));

        numIdentidad.setBackground(new java.awt.Color(241, 231, 197));
        numIdentidad.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        numIdentidad.setBorder(null);
        numIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numIdentidadActionPerformed(evt);
            }
        });
        numIdentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numIdentidadKeyReleased(evt);
            }
        });
        jPanel2.add(numIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 279, 23));

        nombresPsico.setBackground(new java.awt.Color(241, 231, 197));
        nombresPsico.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        nombresPsico.setBorder(null);
        nombresPsico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresPsicoActionPerformed(evt);
            }
        });
        nombresPsico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombresPsicoKeyReleased(evt);
            }
        });
        jPanel2.add(nombresPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 279, 23));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/id-card (2).png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/user (1).png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/user (1).png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/telephone (1).png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/id-card (2).png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 312, -1, 50));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/calendar (2).png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serenty/imagenes/vacancy.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonoPsicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoPsicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoPsicoActionPerformed

    private void HIDEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HIDEMouseClicked
        // TODO add your handling code here:
        passwordPsico.setEchoChar((char)0);
        HIDE.setVisible(false);
        HIDE.setVisible(false);
        SHOW.setVisible(true);
        SHOW.setVisible(true);
    }//GEN-LAST:event_HIDEMouseClicked

    private void SHOWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SHOWMouseClicked
        // TODO add your handling code here:
        passwordPsico.setEchoChar((char)8226);
        HIDE.setVisible(true);
        HIDE.setVisible(true);
        SHOW.setVisible(false);
        SHOW.setVisible(false);
    }//GEN-LAST:event_SHOWMouseClicked

    private void cerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerrar1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String correo = correoPsico.getText();
        String contrasenia = passwordPsico.getText();
        String rol = "Psicologo";
        
        String id_psico = numIdentidad.getText();
        String nombres = nombresPsico.getText();
        String apellidos = apellidosPsico.getText();
        String genero = selectGenero.getSelectedItem().toString();
        String especia = especialidad.getText();
        
        Date fecha_naci = fechaNacimiento.getDate();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String fecha_formateada = simpleDateFormat.format(fecha_naci);
        
        String telefono = telefonoPsico.getText();
        String tipo_entida = selectEntidad.getSelectedItem().toString();
        
        Date fechaLimite = new Date(98, 0, 1);
        
        if(correo.isEmpty()||contrasenia.isEmpty()||id_psico.isEmpty()||nombres.isEmpty()||apellidos.isEmpty()||genero.isEmpty()||genero.equals("Seleccionar")||especia.isEmpty()||fecha_naci == null||telefono.isEmpty()||tipo_entida.isEmpty()||tipo_entida.equals("Seleccionar")){
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if (fecha_naci.before(fechaLimite)) {
                if (telefono.matches("\\d+") && id_psico.matches("\\d+")){
                    
                    if(genero.equals("Masculino")){
                        genero = "M";
                    }else if(genero.equals("Femenino")){
                        genero = "F";
                    }else if(genero.equals("Otro")){
                        genero = "O";
                    }
                    
                    if(Constantes.validarCorreo(correo)){
                        AVISO.setVisible(false);
                        
                        try{                           
                            PreparedStatement psUsuario = (PreparedStatement) cn.prepareStatement(String.format(ConsultasDB.INSERT_INTO_USUARIO, correo, contrasenia, rol));   
                            psUsuario.executeUpdate();
                            
                            PreparedStatement psPsicologo = (PreparedStatement) cn.prepareStatement(String.format(ConsultasDB.INSERT_INTO_PSICOLOGO, id_psico,"Cedula", nombres, apellidos, telefono, genero, tipo_entida, especia, fecha_formateada));
                            psPsicologo.executeUpdate();
                            
                            JOptionPane.showMessageDialog(null, "Datos registrados correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                            IniciarSesionUsuario iniciarSesionUsuario = new IniciarSesionUsuario();
                            iniciarSesionUsuario.setVisible(true);
                            this.setVisible(false);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                        }
                        
                    }else{
                        AVISO.setVisible(true);
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Solo puede ingresar números en los campos número de identificación y teléfono", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Debe tener mínimo 25 años", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        OpcionesUsuario opcionesUsuario = new OpcionesUsuario();
        opcionesUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void telefonoPsicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoPsicoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoPsicoKeyReleased

    private void passwordPsicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPsicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPsicoActionPerformed

    private void selectEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectEntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectEntidadActionPerformed

    private void correoPsicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoPsicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoPsicoActionPerformed

    private void correoPsicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoPsicoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_correoPsicoKeyReleased

    private void especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadActionPerformed

    private void especialidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_especialidadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadKeyReleased

    private void apellidosPsicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosPsicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosPsicoActionPerformed

    private void apellidosPsicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosPsicoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosPsicoKeyReleased

    private void selectGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectGeneroActionPerformed

    private void numIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numIdentidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numIdentidadActionPerformed

    private void numIdentidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numIdentidadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_numIdentidadKeyReleased

    private void nombresPsicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresPsicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresPsicoActionPerformed

    private void nombresPsicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresPsicoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresPsicoKeyReleased
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AVISO;
    private javax.swing.JLabel HIDE;
    private javax.swing.JLabel SHOW;
    private javax.swing.JTextField apellidosPsico;
    private javax.swing.JLabel cerrar1;
    private javax.swing.JTextField correoPsico;
    private javax.swing.JTextField especialidad;
    private com.toedter.calendar.JCalendar fechaNacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField nombresPsico;
    private javax.swing.JTextField numIdentidad;
    private javax.swing.JPasswordField passwordPsico;
    private javax.swing.JComboBox<String> selectEntidad;
    private javax.swing.JComboBox<String> selectGenero;
    private javax.swing.JTextField telefonoPsico;
    // End of variables declaration//GEN-END:variables
void Limpiar(){
    
    telefonoPsico.setText("");
    especialidad.setText("");
 
}

}
